### ISSUE TITLE
Error during compilation in Osx 11.0

### ISSUE THREAD

**Issue by soreno123** [labstreaminglayer/liblsl-Matlab#21]
Hello,
When trying to compile with MatLab r2020a and 11.0 i get this error:

> Error using mex
> [cboulay snipped out warnings]
> /Users/soren/bci/liblsl-Matlab/bin/../mex/lsl_pull_chunk_d.c:99:13: error: implicitly declaring library function
> 'memcpy' with type 'void *(void *, const void *, unsigned long)' [-Werror,-Wimplicit-function-declaration]
>             memcpy(chunkptr,(*cur)->buffer,sizeof(double)*numchannels);
>             ^
> /Users/soren/bci/liblsl-Matlab/bin/../mex/lsl_pull_chunk_d.c:99:13: note: include the header <string.h> or explicitly
> provide a declaration for 'memcpy'
> 5 warnings and 1 error generated.
> 
> 
> Error in build_mex (line 31)
> 		mex('-I../../liblsl/include','-L.', libs{:}, ['../mex/', f.name]);
> 

I'm using latest version of Xcode (12.3) and the lib-lsl is liblsl.1.14.0.dylib compiled by myself.
Any Hint?
Thanks!

**Comment by soreno123** [comment]
Resolved after adding
#include <strings.h> in following files
lsl_push_sample.c
lsl_pull_sample_d.c
lsl_pull_sample_buf.c
lsl_pull_chunk_d.c

**Comment by cboulay** [comment]
Thanks very much for your report and solution. I'm going to reopen this until we've had a chance to update the source.
